# Generated by Django 5.0 on 2023-12-27 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medics', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medproduct',
            name='medic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medics.medic'),
        ),
        migrations.AddField(
            model_name='medproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='medsalarypayment',
            name='medic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medics.medic'),
        ),
    ]
